from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget.setObjectName("centralwidget")
        self.Nodes = QtWidgets.QLabel(self.centralwidget)
        self.Nodes.setGeometry(QtCore.QRect(50, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Nodes.setFont(font)
        self.Nodes.setObjectName("Nodes")
        self.Rods = QtWidgets.QLabel(self.centralwidget)
        self.Rods.setGeometry(QtCore.QRect(600, 10, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Rods.setFont(font)
        self.Rods.setObjectName("Rods")
        self.refresh = QtWidgets.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(1550, 820, 300, 100))
        self.refresh.setObjectName("refresh")
        self.paint_widget = QtWidgets.QGraphicsView(self.centralwidget)
        self.paint_widget.setGeometry(QtCore.QRect(10, 270, 1500, 650))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paint_widget.sizePolicy().hasHeightForWidth())
        self.paint_widget.setSizePolicy(sizePolicy)
        self.paint_widget.setMouseTracking(True)
        self.paint_widget.setAutoFillBackground(True)
        self.paint_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.paint_widget.setObjectName("paint_widget")
        self.Forces = QtWidgets.QLabel(self.centralwidget)
        self.Forces.setGeometry(QtCore.QRect(1240, 10, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Forces.setFont(font)
        self.Forces.setObjectName("Forces")
        self.left_support = QtWidgets.QPushButton(self.centralwidget)
        self.left_support.setGeometry(QtCore.QRect(1600, 580, 200, 50))
        self.left_support.setAutoRepeat(False)
        self.left_support.setObjectName("left_support")
        self.right_support = QtWidgets.QPushButton(self.centralwidget)
        self.right_support.setGeometry(QtCore.QRect(1600, 640, 200, 50))
        self.right_support.setAutoRepeat(False)
        self.right_support.setObjectName("right_support")
        self.dual_support = QtWidgets.QPushButton(self.centralwidget)
        self.dual_support.setGeometry(QtCore.QRect(1600, 720, 200, 50))
        self.dual_support.setAutoRepeat(False)
        self.dual_support.setObjectName("dual_support")
        self.NodeTable = QtWidgets.QTextEdit(self.centralwidget)
        self.NodeTable.setGeometry(QtCore.QRect(105, 50, 300, 100))
        self.NodeTable.setObjectName("NodeTable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 250, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(635, 60, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 130, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(600, 195, 90, 30))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(700, 10, 500, 40))
        self.label_5.setObjectName("label_5")
        self.RodTable_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.RodTable_3.setGeometry(QtCore.QRect(700, 50, 210, 40))
        self.RodTable_3.setObjectName("RodTable_3")
        self.RodTable_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.RodTable_4.setGeometry(QtCore.QRect(700, 120, 210, 40))
        self.RodTable_4.setObjectName("RodTable_4")
        self.RodTable_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.RodTable_5.setGeometry(QtCore.QRect(700, 190, 210, 40))
        self.RodTable_5.setObjectName("RodTable_5")
        self.ForceTable_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.ForceTable_1.setGeometry(QtCore.QRect(1300, 50, 210, 40))
        self.ForceTable_1.setObjectName("ForceTable_1")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1200, 45, 100, 50))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1135, 110, 200, 55))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1230, 196, 65, 25))
        self.label_8.setObjectName("label_8")
        self.ForceTable_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.ForceTable_2.setGeometry(QtCore.QRect(1300, 120, 210, 40))
        self.ForceTable_2.setObjectName("ForceTable_2")
        self.ForceTable_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.ForceTable_3.setGeometry(QtCore.QRect(1300, 190, 210, 40))
        self.ForceTable_3.setObjectName("ForceTable_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1300, 15, 200, 20))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_calc_2 = QtWidgets.QMenu(self.menubar)
        self.menu_calc_2.setObjectName("menu_calc_2")
        self.menu_info = QtWidgets.QMenu(self.menubar)
        self.menu_info.setObjectName("menu_info")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu_calc = QtWidgets.QAction(MainWindow)
        self.menu_calc.setObjectName("menu_calc")
        self.show_graph = QtWidgets.QAction(MainWindow)
        self.show_graph.setObjectName("show_graph")
        self.menu_help = QtWidgets.QAction(MainWindow)
        self.menu_help.setObjectName("menu_help")
        self.menu_about = QtWidgets.QAction(MainWindow)
        self.menu_about.setObjectName("menu_about")
        self.menu_save = QtWidgets.QAction(MainWindow)
        self.menu_save.setWhatsThis("")
        self.menu_save.setObjectName("menu_save")
        self.menu_open = QtWidgets.QAction(MainWindow)
        self.menu_open.setObjectName("menu_open")
        self.menu_calc_2.addAction(self.menu_calc)
        self.menu_calc_2.addAction(self.show_graph)
        self.menu_info.addAction(self.menu_help)
        self.menu_info.addSeparator()
        self.menu_info.addAction(self.menu_about)
        self.menu_file.addAction(self.menu_save)
        self.menu_file.addAction(self.menu_open)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_calc_2.menuAction())
        self.menubar.addAction(self.menu_info.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ST_SAPRv0.1"))
        self.Nodes.setText(_translate("MainWindow", "Узлы:"))
        self.Rods.setText(_translate("MainWindow", "Стержни:"))
        self.refresh.setText(_translate("MainWindow", "Отрисовка эпюры"))
        self.Forces.setText(_translate("MainWindow", "Силы:"))
        self.left_support.setText(_translate("MainWindow", "Левая заделка"))
        self.right_support.setText(_translate("MainWindow", "Правая заделка"))
        self.dual_support.setText(_translate("MainWindow", "Обе заделки"))
        self.label.setText(_translate("MainWindow", "(Введите координаты узлов по оси X \nчерез пробел)"))
        self.label_2.setText(_translate("MainWindow", "Площадь:"))
        self.label_3.setText(_translate("MainWindow", "Упругость:"))
        self.label_4.setText(_translate("MainWindow", "Максимальное\n  напряжение:"))
        self.label_5.setText(_translate("MainWindow", "(Ввод для каждого стержня - соответствующее значение \nв соответствующую строку, разделяя пробелами)"))
        self.label_6.setText(_translate("MainWindow", "Узел/стержень:"))
        self.label_7.setText(_translate("MainWindow", "\t\tТип силы:\n(Сосред - 1 | Распред - 2)"))
        self.label_8.setText(_translate("MainWindow", "Значение:"))
        self.label_9.setText(_translate("MainWindow", "(Ввод параметров через пробел)"))
        self.menu_calc_2.setTitle(_translate("MainWindow", "Рассчет"))
        #self.menu_info.setTitle(_translate("MainWindow", "Информация"))
        self.menu_file.setTitle(_translate("MainWindow", "Файл"))
        self.action.setText(_translate("MainWindow", "Сохранить"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))
        self.menu_calc.setText(_translate("MainWindow", "Рассчет"))
        self.menu_calc.setStatusTip(_translate("MainWindow", "Рассчитать нагрузки"))
        self.menu_calc.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.show_graph.setText(_translate("MainWindow", "Эпюры"))
        self.show_graph.setStatusTip(_translate("MainWindow", "Отобразить эпюры"))
        self.show_graph.setShortcut(_translate("MainWindow", "Ctrl+G"))
        #self.menu_help.setText(_translate("MainWindow", "Помощь"))
        #self.menu_about.setText(_translate("MainWindow", "О разработчике"))
        self.menu_save.setText(_translate("MainWindow", "Сохранить"))
        self.menu_save.setIconText(_translate("MainWindow", "Сохранить"))
        self.menu_save.setToolTip(_translate("MainWindow", "Сохранить"))
        self.menu_save.setStatusTip(_translate("MainWindow", "Сохранить файл"))
        self.menu_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menu_open.setText(_translate("MainWindow", "Открыть"))
        self.menu_open.setStatusTip(_translate("MainWindow", "Открыть файл"))
        self.menu_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.setWindowState(QtCore.Qt.WindowMaximized)
